name: Run Tests

on: 
    push:
      branches: ["main"]
    pull_request:
      branches: ["*"]
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            max-parallel: 4
            fail-fast: false
            matrix:
              version: ["5.1", "daily"]
              os: [macos-latest, windows-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v5

            - uses: BradyAJohnston/setup-blender@v5
              with:
                version: ${{ matrix.version }}
            - name: Install in Blender
              run: blender -b -P tests/python.py -- -m pip install ".[test]"
            - name: Run Tests in Blender
              run: blender -b -P tests/run.py -- -vv tests --cov --cov-report=xml
    

    
